var data = {
   
    "fr": {
        "001": "Moi",
        "002": "Profil",
        "003": "Contact",
        "004": "Qualités",
        "005": "Compétences",
        "006": "Transversales",
        "007": "Techniques",
        "008": "Experiences",
        "009": "En tant qu'étudiant",
        "010": "En informatique",
        "011": "PROFIL",
        "111": "Je suis un jeune passionné par la technologie et le numérique. C'est pourquoi je souhaite devenir développeur web, un métier en constante évolution de nos jours.J'ai principalement poursuivi mon apprentissage de manière autodidacte sans encore avoir commencé d'études universitaires.",
        "012": "Parcours",
        "013": "Année préparatoire PROGRAMME SESAME",
        "014": "ExBaccalauréat Série S Mention Bien",
        "015": "Lycée Ambatolampy 104 3 années scolaires",
        "017": "BEPC Option A 3éme rang (CISCO)",
        "018": "COMPETENCES",
        "019": "EXPERIENCES",
        "020": "En développement Web",
        "021": "Réalisation des mini-projets.",
        "022": "Participation à des défis.",
        "023": "Membre du club d'informatique.",
        "024": "En tant qu'étudiants",
        "025": "Chef de classe",
        "026": "Chef de TD",
        "027": "Répresentant de classe",
        "028": "Qualités",
        "029": "Serieux",
        "030": "Responsable",
        "031": "Attentif",
        "032": "Autonome",
        "033": "Langues",
        "034": "Passions",
        "035": "Coder",
        "036": "Jeux-Vidéos",
        "037": "Film",
        "038": "Musique",
        "039": "Piano",
        "040": "Contactez-moi!",
    },
    "en": {
        "001": "Me",
        "002": "Profile",
        "003": "Contact",
        "004": "Qualities",
        "005": "Skills",
        "006": "Soft_skills",
        "007": "Hard-skills",
        "008": "Experiences",
        "009": "As a student",
        "010": "In computing",
        "011": "PROFILE",
        "111": "I am a young enthusiast about technology and digital. That's why I want to become a web developer, a profession that is constantly evolving nowadays. I have mainly pursued my learning in a self-taught manner without starting university studies yet.",
        "012": "Career",
        "013": "Preparatory Year  PROGRAMME SESAME",
        "014": "High School Diploma Series S with Honors",
        "015": "Ambatolampy High School 104",
        "017": "Junior High School Diploma Option A",
        "018": "SKILLS",
        "019": "EXPERIENCES",
        "020": "In Web development",
        "021": "Completion of mini-projects.",
        "022": "Participation in challenges.",
        "023": "Member of the computer club.",
        "024": "As students",
        "025": "Class leader",
        "026": "TD leader",
        "027": "Class representative",
        "028": "Qualities",
        "029": "Serious",
        "030": "Responsible",
        "031": "Attentive",
        "032": "Autonomous",
        "033": "Languages",
        "034": "Passions",
        "035": "Coding",
        "036": "Video games",
        "037": "Movies",
        "038": "Music",
        "039": "Piano",
        "040": "Contact me!"
    }
}
